### PR TITLE
fix typo in Tighten depends on pcre3 to workaround symbols brokeness

### PR DESCRIPTION
**Pull request by haeber**

### CODE REVIEW

**Comment by haeber** [comment]
@oerdnj The typo broke my vagrant build, please test, merge and deploy as soon as possible.

**Comment by oerdnj** [comment]
Phew, at least it only broke phpX.Y-dev... Merged, thanks.

**Comment by haeber** [comment]
@oerdnj In githib it's not marked as merged, where did you merge it?

@oerdnj You are right, it only broke my php7.0-dev.

**Comment by oerdnj** [comment]
github is just a push mirror, git.debian.org is a primary git repository, so I have to do a manual merge, it should be pushed any moment now.

**Comment by oerdnj** [comment]
https://github.com/pkg-php/php/commit/c2edd2cb923e88b7e0252ef1ef282d26a1814910

**Comment by haeber** [comment]
@oerdnj Thanks. Good day.

**Pull request closed without merging**
